### ISSUE TITLE
运行label报错：ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by SmartBest-Zhi** [opendatalab/labelU#91]
运行labelu报错，版本
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Programs\SDK\Python\Python3\Scripts\labelu.exe\__main__.py", line 4, in <module>
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\labelu\main.py", line 91, in <module>
    run_sqlite_migrations()
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\labelu\alembic_labelu\run_migrate.py", line 23, in run_sqlite_migrations
    for revision in script.walk_revisions():
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\base.py", line 301, in walk_revisions
    for rev in self.revision_map.iterate_revisions(
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 813, in iterate_revisions
    revisions, heads = fn(
                       ^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 1438, in _collect_upgrade_revisions
    for rev in self._parse_upgrade_target(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 1229, in _parse_upgrade_target
    return self.get_revisions(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 545, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(id_)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 767, in _resolve_revision_number
    self._revision_map
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\revision.py", line 210, in _revision_map
    for revision in self._generator():
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\base.py", line 155, in _load_revisions
    script = Script._from_filename(self, dir_name, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\script\base.py", line 1042, in _from_filename
    module = util.load_python_file(dir_, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\SDK\Python\Python3\Lib\site-packages\labelu\alembic_labelu\versions\bc8fcb35b66b_add_media_and_pre_annotation.py", line 8, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by gary-Shen** [comment]
看起来是依赖没装上，运行了 poetry install 报的吗？

**Comment by SmartBest-Zhi** [comment]
> 看起来是依赖没装上，运行了 poetry install 报的吗？

```
C:\Users\27699>pip install labelu
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: labelu in d:\programs\sdk\python\python3\lib\site-packages (1.0.2)
Requirement already satisfied: aiofiles<23.0.0,>=22.1.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (22.1.0)
Requirement already satisfied: alembic<2.0.0,>=1.9.4 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (1.13.1)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (1.4.4)
Requirement already satisfied: email-validator<2.0.0,>=1.3.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (1.3.1)
Requirement already satisfied: fastapi<0.87.0,>=0.86.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (0.86.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (0.6.0)
Requirement already satisfied: passlib<2.0.0,>=1.7.4 in d:\programs\sdk\python\python3\lib\site-packages (from passlib[bcrypt]<2.0.0,>=1.7.4->labelu) (1.7.4)
Requirement already satisfied: pillow<10.0.0,>=9.3.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (9.5.0)
Requirement already satisfied: python-dotenv<0.22.0,>=0.21.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (0.21.1)
Requirement already satisfied: python-jose<4.0.0,>=3.3.0 in d:\programs\sdk\python\python3\lib\site-packages (from python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (3.3.0)
Requirement already satisfied: python-multipart<0.0.6,>=0.0.5 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (0.0.5)
Requirement already satisfied: sqlalchemy<2.0.0,>=1.4.43 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (1.4.52)
Requirement already satisfied: typer<0.8.0,>=0.7.0 in d:\programs\sdk\python\python3\lib\site-packages (from typer[all]<0.8.0,>=0.7.0->labelu) (0.7.0)
Requirement already satisfied: uvicorn<0.20.0,>=0.19.0 in d:\programs\sdk\python\python3\lib\site-packages (from labelu) (0.19.0)
Requirement already satisfied: Mako in d:\programs\sdk\python\python3\lib\site-packages (from alembic<2.0.0,>=1.9.4->labelu) (1.3.2)
Requirement already satisfied: typing-extensions>=4 in d:\programs\sdk\python\python3\lib\site-packages (from alembic<2.0.0,>=1.9.4->labelu) (4.10.0)
Requirement already satisfied: dnspython>=1.15.0 in d:\programs\sdk\python\python3\lib\site-packages (from email-validator<2.0.0,>=1.3.0->labelu) (2.6.1)
Requirement already satisfied: idna>=2.0.0 in d:\programs\sdk\python\python3\lib\site-packages (from email-validator<2.0.0,>=1.3.0->labelu) (3.6)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in d:\programs\sdk\python\python3\lib\site-packages (from fastapi<0.87.0,>=0.86.0->labelu) (1.10.15)
Requirement already satisfied: starlette==0.20.4 in d:\programs\sdk\python\python3\lib\site-packages (from fastapi<0.87.0,>=0.86.0->labelu) (0.20.4)
Requirement already satisfied: anyio<5,>=3.4.0 in d:\programs\sdk\python\python3\lib\site-packages (from starlette==0.20.4->fastapi<0.87.0,>=0.86.0->labelu) (4.3.0)
Requirement already satisfied: colorama>=0.3.4 in d:\programs\sdk\python\python3\lib\site-packages (from loguru<0.7.0,>=0.6.0->labelu) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in d:\programs\sdk\python\python3\lib\site-packages (from loguru<0.7.0,>=0.6.0->labelu) (1.1.0)
Requirement already satisfied: bcrypt>=3.1.0 in d:\programs\sdk\python\python3\lib\site-packages (from passlib[bcrypt]<2.0.0,>=1.7.4->labelu) (4.1.2)
Requirement already satisfied: ecdsa!=0.15 in d:\programs\sdk\python\python3\lib\site-packages (from python-jose<4.0.0,>=3.3.0->python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (0.18.0)
Requirement already satisfied: rsa in d:\programs\sdk\python\python3\lib\site-packages (from python-jose<4.0.0,>=3.3.0->python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (4.9)
Requirement already satisfied: pyasn1 in d:\programs\sdk\python\python3\lib\site-packages (from python-jose<4.0.0,>=3.3.0->python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (0.6.0)
Requirement already satisfied: cryptography>=3.4.0 in d:\programs\sdk\python\python3\lib\site-packages (from python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (42.0.5)
Requirement already satisfied: six>=1.4.0 in d:\programs\sdk\python\python3\lib\site-packages (from python-multipart<0.0.6,>=0.0.5->labelu) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\programs\sdk\python\python3\lib\site-packages (from sqlalchemy<2.0.0,>=1.4.43->labelu) (3.0.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in d:\programs\sdk\python\python3\lib\site-packages (from typer<0.8.0,>=0.7.0->typer[all]<0.8.0,>=0.7.0->labelu) (8.1.7)
Requirement already satisfied: shellingham<2.0.0,>=1.3.0 in d:\programs\sdk\python\python3\lib\site-packages (from typer[all]<0.8.0,>=0.7.0->labelu) (1.5.4)
Requirement already satisfied: rich<13.0.0,>=10.11.0 in d:\programs\sdk\python\python3\lib\site-packages (from typer[all]<0.8.0,>=0.7.0->labelu) (12.6.0)
Requirement already satisfied: h11>=0.8 in d:\programs\sdk\python\python3\lib\site-packages (from uvicorn<0.20.0,>=0.19.0->labelu) (0.14.0)
Requirement already satisfied: cffi>=1.12 in d:\programs\sdk\python\python3\lib\site-packages (from cryptography>=3.4.0->python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (1.16.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in d:\programs\sdk\python\python3\lib\site-packages (from rich<13.0.0,>=10.11.0->typer[all]<0.8.0,>=0.7.0->labelu) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in d:\programs\sdk\python\python3\lib\site-packages (from rich<13.0.0,>=10.11.0->typer[all]<0.8.0,>=0.7.0->labelu) (2.17.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\programs\sdk\python\python3\lib\site-packages (from Mako->alembic<2.0.0,>=1.9.4->labelu) (2.1.5)
Requirement already satisfied: sniffio>=1.1 in d:\programs\sdk\python\python3\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.20.4->fastapi<0.87.0,>=0.86.0->labelu) (1.3.1)
Requirement already satisfied: pycparser in d:\programs\sdk\python\python3\lib\site-packages (from cffi>=1.12->cryptography>=3.4.0->python-jose[cryptography]<4.0.0,>=3.3.0->labelu) (2.22)

C:\Users\27699>labelu
```

**Comment by gary-Shen** [comment]
应该是漏了这个包，先手动安装一下这个依赖，晚点更新一下 pyproject.toml。

**Comment by gary-Shen** [comment]
Sorry, Python 是什么版本？

**Comment by SmartBest-Zhi** [comment]
> Sorry, Python 是什么版本？

```
C:\Users\27699>python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by gary-Shen** [comment]
> > Sorry, Python 是什么版本？
> 
> ```
> C:\Users\27699>python
> Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>
> ```

建议用 python 3.7 再安装试试看？
